language: java
dist: trusty

jdk:
- openjdk8

env:
  global:
  - secure: "h35jdOh9+ehcJHk12ykJ1d6yZ1FIvoFX58hvpAA/YYWsJyaY/ZFtbP3lO3ONPZPmoaZz+kR/1Ls2An+Iuz7Q8HalsVtCjpR+HWXkYVclI5I5zp52ajwoWncHN71o6tRIgRbmK+YlxP7NJhu2xO8wyFrEP84LkNJ6rxseU5sTKoSfT9kjmjY27jHER9+nG+eBZe3+Bngs0bF9dWaD4xK0cDPrbgu8F03nxWgsGmXLigq9FePYUOs0C1jRTeVdzLn43NepgJL4tOrg4t1sVRlmCb+d8VgI7Gl+fvl6y25hWhYDD60OJz+npEIFFDfUvsums/DWHuSFLnjSOT/8Qz/XGQd/f+Ln/4Vfo/ohW5L79DmtYnVqDrU/Lw8PQzQsg7Ewbcj82a45SM60O78t2FbCXY4bQJkwGGqISqMcxs0dmZjKW5iSjIGFrea8fp6zVMgxI0hIh5uip9dtvtZ6nfikpBHBgvGokUa8fxlp9WIciZPq5q7rbCMH2OCKrHtCTyyDV0Ezr+rwZFsmkWxDr2xpqtrj7sWasYMP+i/dXwoJ6vc47sIpNaki0U73e1bsHK6mT3fLDlaK7CyLb1oNezcOds4liV3B0znYt0Hjt7AIolYx3m/7Lo3fIjDyAH6J3Eq+eEfYpJ0G2HpYeBBAY/4zt+pT3Nud0/sX3hPmh7NY+Ig="
  - secure: "Fb09utnSuvCAgm96W9SCOk2nkHWgsRCosu4gYG4/b5azyjn6XxQ2cHnGQTW61ttnnyQGBQ9F7SNPYChwdZCHHJT1ti+UrKD10B++aehdgvPlRjmHJjmD3LTYLXVS8TLdLiZYcKhOeptzmbG/j7TMuD2nbj2MA7YzljeQX26SNknoWDDo9DVL3mCuOn7qGRZ3WJXha/vG33I0i4i3dCI8z6xeJsxo7nkogJ4NvdwoWro2RVlz2S3hqAyfRT+KkrgzMc0sbw/0XwoBqtgG6y9bznDPhDgQhQl25pmbGEss+GAIYMZ1OruP1L9iDl542IyG0wlihRvDdU4fDv5WrFtEuFVHoSjYb+GygX4ou4/ItKBvrIT3BiVrgpGm1DxPIICg4Un7PQ+N+LB1dXD6bBMmU+hu0p4adsia3PjT6GvAttUXyO9XYr0iL9sNu4Jp+EagjGwJcso3plEdDJOOizgBxUFsY4+9hViAFPo1YHBtringb0Y/brHIZ5RxjtiUjBm6BkYaZIJb04nfqR6TV/DpVM3yhb72l/BBk662phwi5mFwjH43HxS13I3B4yXk+Nhveyi2YgkZ90IWI8aKkMzK82mAUIM5yjMBqlOo5cGiUb2sNIXWjJ2IK8HjGiKjd5ko1Swg4ioiMwi5wZ7gPMa6hRBCkaxOfsdo38+Qcz4or30="
  - secure: "Y28a6ZnggyjLVUwZRsPkeXlCRukIqDnHsb8y+n3vREEvr5BM7x9AgCdz40gaOyRAn0vubVyjDLeNAp9vNBxnsR9sEq3vS/qpEXwBAybbb4GKUtgehySOYoH6JgZzduToHe1qiBzmRcZIawl6DCGvTnG1MUqdqXbKtI2JuUCklXR61U7D/dc0mnUMiVCobSG/E6QQixSt22+oDJFqsR34l3K/NOlic2N2oCrgj7IT5e9uObBbwFhSowl1eNESAywiXbb/7SG5V8UGgSHkjOTHjOP6xWlRBxqyAtrf79i0LnUUPEHp7ivTtIuGKolrFvQml8cOdoqHTYAtrbuepu3EkVFYD6MAICNcOpev2rnkLUrMKkUHUjtkXE9Xx4bFTotZx+Xlys/uKHXq7agYpdmit9k4AdN8fBaC/PX91yQouz2bVec46oZo5mJb9wB3dwh7Egt6/3fnF8CItZfblsBkB6IeX4nBD2jsSgJI1k00cAWc43NLfbgedklze7CDvFrd3y/uzJWNJKkhjHomUCEPux0bu1CDWi9bSJr8Ft/RxnzpDcBo87+8pCV/92BDWA64FPcCp4VJD9AcdU0RjBHVEfo22SYI/hqWr1na/BjcGPoRql2OLVODuz0zDBix7oOdjswqnsYFQbHL6sLpQRMo9Ynz7EDprpYWrVG7VvnZWEc="

cache:
  directories:
  - "$HOME/.m2"

install: mvn clean install -DskipTests=true -V -U
script: mvn test

after_success:
# Deploy to OSSHR
- if [[ $TRAVIS_PULL_REQUEST == "false" && ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG) ]]; then
    openssl aes-256-cbc -K $encrypted_0c99a18c6443_key -iv $encrypted_0c99a18c6443_iv -in gpg.tar.gz.enc -out gpg.tar.gz -d;
    tar xvf gpg.tar.gz;
    mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
  fi
